function Hd = filter_mcf_channelizer
%FILTER_MCF_CHANNELIZER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 28-Jun-2019 17:36:41

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 23040000;  % Sampling Frequency

Fpass = 700000;          % Passband Frequency
Fstop = 1000000;         % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 1e-05;           % Stopband Attenuation
flag  = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fpass Fstop]/(Fs/2), [1 0], [Dstop Dpass]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

% [EOF]
